# Generated by Django 5.0.6 on 2024-07-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, 
                related_name='items', to='outlet.category', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, 
                related_name='items', to='outlet.itemtype', null=True, blank=True),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
                    related_name='subcategories', to='outlet.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='itemtype',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='outlet.subcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, 
                related_name='items', to='outlet.subcategory', null=True, blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together={('name', 'subcategory')},
        ),
    ]
