# Generated by Django 5.0.6 on 2024-07-02 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0005_alter_item_category_alter_item_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outlet.itemtype'),
        ),
    ]
