# Generated by Django 5.0.6 on 2024-07-04 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0007_alter_item_item_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
    ]
