# Generated by Django 5.0.6 on 2024-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0008_alter_subcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
