# Generated by Django 5.0.6 on 2024-07-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0009_alter_item_slug_alter_itemtype_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="outlet.category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="outlet.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="subcategory",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="outlet.subcategory",
            ),
        ),
    ]
