# Generated by Django 5.0.6 on 2024-07-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0010_alter_item_category_alter_item_item_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
                ("slug", models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
                ("slug", models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="item_age",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="outlet.agegroup",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_gender",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="outlet.gender",
            ),
        ),
    ]
