# Generated by Django 5.0.6 on 2024-07-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0011_agegroup_gender_item_item_age_item_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_age",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="outlet.agegroup",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="outlet.gender",
            ),
        ),
    ]
